import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const ROLES = ['FRONTEND', 'BACKEND', 'FULLSTACK', 'DESIGN', 'QA', 'DATA', 'PLATFORM'] as const;

interface SeedEmployee {
  email: string;
  fullName: string;
  primaryRole: string;
  currentAllocationPercentage: number;
  availabilityDate: Date;
  geographicLocation: string;
  skills: { skill: string; proficiencyLevel: number }[];
}

const employees: SeedEmployee[] = [
  // ==================== ORIGINAL 10 EMPLOYEES ====================
  {
    email: 'thabo.mokoena@standardbank.co.za',
    fullName: 'Thabo Mokoena',
    primaryRole: 'FULLSTACK',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-15'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'Node.js', proficiencyLevel: 4 },
      { skill: 'PostgreSQL', proficiencyLevel: 4 },
      { skill: 'Architecture', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'naledi.dlamini@standardbank.co.za',
    fullName: 'Naledi Dlamini',
    primaryRole: 'FRONTEND',
    currentAllocationPercentage: 30,
    availabilityDate: new Date('2024-01-20'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'Tailwind CSS', proficiencyLevel: 5 },
      { skill: 'Figma', proficiencyLevel: 4 },
      { skill: 'Accessibility', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'sipho.nkosi@standardbank.co.za',
    fullName: 'Sipho Nkosi',
    primaryRole: 'BACKEND',
    currentAllocationPercentage: 60,
    availabilityDate: new Date('2024-02-01'),
    geographicLocation: 'Pretoria, ZA',
    skills: [
      { skill: 'Node.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'PostgreSQL', proficiencyLevel: 5 },
      { skill: 'Docker', proficiencyLevel: 4 },
      { skill: 'AWS', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'lerato.molefe@standardbank.co.za',
    fullName: 'Lerato Molefe',
    primaryRole: 'DESIGN',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-10'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Figma', proficiencyLevel: 5 },
      { skill: 'UX Research', proficiencyLevel: 5 },
      { skill: 'Accessibility', proficiencyLevel: 4 },
      { skill: 'Design Systems', proficiencyLevel: 5 },
      { skill: 'React', proficiencyLevel: 2 },
    ],
  },
  {
    email: 'mandla.zulu@standardbank.co.za',
    fullName: 'Mandla Zulu',
    primaryRole: 'QA',
    currentAllocationPercentage: 20,
    availabilityDate: new Date('2024-01-18'),
    geographicLocation: 'Durban, ZA',
    skills: [
      { skill: 'Playwright', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'API Testing', proficiencyLevel: 5 },
      { skill: 'Performance Testing', proficiencyLevel: 4 },
      { skill: 'CI/CD', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'ayanda.mbeki@standardbank.co.za',
    fullName: 'Ayanda Mbeki',
    primaryRole: 'DATA',
    currentAllocationPercentage: 80,
    availabilityDate: new Date('2024-03-01'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Python', proficiencyLevel: 5 },
      { skill: 'SQL', proficiencyLevel: 5 },
      { skill: 'Data Modeling', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 3 },
      { skill: 'Kafka', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'zanele.khumalo@standardbank.co.za',
    fullName: 'Zanele Khumalo',
    primaryRole: 'PLATFORM',
    currentAllocationPercentage: 40,
    availabilityDate: new Date('2024-01-25'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'AWS', proficiencyLevel: 5 },
      { skill: 'Docker', proficiencyLevel: 5 },
      { skill: 'Kubernetes', proficiencyLevel: 4 },
      { skill: 'Terraform', proficiencyLevel: 5 },
      { skill: 'CI/CD', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'bongani.sithole@standardbank.co.za',
    fullName: 'Bongani Sithole',
    primaryRole: 'FRONTEND',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-12'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'Next.js', proficiencyLevel: 4 },
      { skill: 'Tailwind CSS', proficiencyLevel: 4 },
      { skill: 'GraphQL', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'precious.ngwenya@standardbank.co.za',
    fullName: 'Precious Ngwenya',
    primaryRole: 'FULLSTACK',
    currentAllocationPercentage: 50,
    availabilityDate: new Date('2024-02-10'),
    geographicLocation: 'Pretoria, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 4 },
      { skill: 'Node.js', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'PostgreSQL', proficiencyLevel: 3 },
      { skill: 'AWS', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'kagiso.mthembu@standardbank.co.za',
    fullName: 'Kagiso Mthembu',
    primaryRole: 'BACKEND',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-08'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Node.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'PostgreSQL', proficiencyLevel: 4 },
      { skill: 'Redis', proficiencyLevel: 4 },
      { skill: 'Architecture', proficiencyLevel: 5 },
    ],
  },

  // ==================== 50 ADDITIONAL EMPLOYEES ====================

  // --- FRONTEND (7 additional) ---
  {
    email: 'pieter.vandermerwe@standardbank.co.za',
    fullName: 'Pieter van der Merwe',
    primaryRole: 'FRONTEND',
    currentAllocationPercentage: 20,
    availabilityDate: new Date('2024-02-05'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'Angular', proficiencyLevel: 3 },
      { skill: 'Accessibility', proficiencyLevel: 4 },
      { skill: 'CSS', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'nomsa.mabaso@standardbank.co.za',
    fullName: 'Nomsa Mabaso',
    primaryRole: 'FRONTEND',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-22'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Vue.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'Tailwind CSS', proficiencyLevel: 5 },
      { skill: 'HTML', proficiencyLevel: 5 },
      { skill: 'CSS', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'ravi.naidoo@standardbank.co.za',
    fullName: 'Ravi Naidoo',
    primaryRole: 'FRONTEND',
    currentAllocationPercentage: 70,
    availabilityDate: new Date('2024-04-01'),
    geographicLocation: 'Durban, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 4 },
      { skill: 'Next.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'GraphQL', proficiencyLevel: 4 },
      { skill: 'Angular', proficiencyLevel: 3 },
      { skill: 'Tailwind CSS', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'chantel.williams@standardbank.co.za',
    fullName: 'Chantel Williams',
    primaryRole: 'FRONTEND',
    currentAllocationPercentage: 40,
    availabilityDate: new Date('2024-03-10'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'Tailwind CSS', proficiencyLevel: 4 },
      { skill: 'Next.js', proficiencyLevel: 3 },
      { skill: 'Accessibility', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'lungile.ndaba@standardbank.co.za',
    fullName: 'Lungile Ndaba',
    primaryRole: 'FRONTEND',
    currentAllocationPercentage: 100,
    availabilityDate: new Date('2024-06-01'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Angular', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'CSS', proficiencyLevel: 4 },
      { skill: 'HTML', proficiencyLevel: 5 },
      { skill: 'React', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'annika.botha@standardbank.co.za',
    fullName: 'Annika Botha',
    primaryRole: 'FRONTEND',
    currentAllocationPercentage: 10,
    availabilityDate: new Date('2024-02-15'),
    geographicLocation: 'Pretoria, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 4 },
      { skill: 'Vue.js', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'Tailwind CSS', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'thandeka.ngubane@standardbank.co.za',
    fullName: 'Thandeka Ngubane',
    primaryRole: 'FRONTEND',
    currentAllocationPercentage: 60,
    availabilityDate: new Date('2024-05-01'),
    geographicLocation: 'Polokwane, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'Next.js', proficiencyLevel: 4 },
      { skill: 'Figma', proficiencyLevel: 3 },
      { skill: 'GraphQL', proficiencyLevel: 4 },
    ],
  },

  // --- BACKEND (7 additional) ---
  {
    email: 'tshepo.mofokeng@standardbank.co.za',
    fullName: 'Tshepo Mofokeng',
    primaryRole: 'BACKEND',
    currentAllocationPercentage: 30,
    availabilityDate: new Date('2024-02-20'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Java', proficiencyLevel: 5 },
      { skill: 'Spring Boot', proficiencyLevel: 5 },
      { skill: 'PostgreSQL', proficiencyLevel: 4 },
      { skill: 'Docker', proficiencyLevel: 4 },
      { skill: 'Redis', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'fatima.patel@standardbank.co.za',
    fullName: 'Fatima Patel',
    primaryRole: 'BACKEND',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-15'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Python', proficiencyLevel: 5 },
      { skill: 'Node.js', proficiencyLevel: 4 },
      { skill: 'PostgreSQL', proficiencyLevel: 5 },
      { skill: 'MongoDB', proficiencyLevel: 4 },
      { skill: 'Docker', proficiencyLevel: 3 },
      { skill: 'Kafka', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'hennie.joubert@standardbank.co.za',
    fullName: 'Hennie Joubert',
    primaryRole: 'BACKEND',
    currentAllocationPercentage: 80,
    availabilityDate: new Date('2024-05-01'),
    geographicLocation: 'Pretoria, ZA',
    skills: [
      { skill: 'Java', proficiencyLevel: 5 },
      { skill: 'Spring Boot', proficiencyLevel: 5 },
      { skill: 'PostgreSQL', proficiencyLevel: 5 },
      { skill: 'Redis', proficiencyLevel: 4 },
      { skill: 'Docker', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'noluthando.gcabashe@standardbank.co.za',
    fullName: 'Noluthando Gcabashe',
    primaryRole: 'BACKEND',
    currentAllocationPercentage: 50,
    availabilityDate: new Date('2024-03-15'),
    geographicLocation: 'Durban, ZA',
    skills: [
      { skill: 'Node.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'MongoDB', proficiencyLevel: 4 },
      { skill: 'Docker', proficiencyLevel: 3 },
      { skill: 'AWS', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'johan.pretorius@standardbank.co.za',
    fullName: 'Johan Pretorius',
    primaryRole: 'BACKEND',
    currentAllocationPercentage: 10,
    availabilityDate: new Date('2024-02-01'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'Node.js', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'PostgreSQL', proficiencyLevel: 5 },
      { skill: 'Redis', proficiencyLevel: 5 },
      { skill: 'Python', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'priya.govender@standardbank.co.za',
    fullName: 'Priya Govender',
    primaryRole: 'BACKEND',
    currentAllocationPercentage: 90,
    availabilityDate: new Date('2024-07-01'),
    geographicLocation: 'Durban, ZA',
    skills: [
      { skill: 'Python', proficiencyLevel: 5 },
      { skill: 'Java', proficiencyLevel: 4 },
      { skill: 'PostgreSQL', proficiencyLevel: 4 },
      { skill: 'Docker', proficiencyLevel: 5 },
      { skill: 'MongoDB', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'mukovhe.nemutandani@standardbank.co.za',
    fullName: 'Mukovhe Nemutandani',
    primaryRole: 'BACKEND',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-28'),
    geographicLocation: 'Polokwane, ZA',
    skills: [
      { skill: 'Node.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'PostgreSQL', proficiencyLevel: 4 },
      { skill: 'Kafka', proficiencyLevel: 5 },
      { skill: 'AWS', proficiencyLevel: 3 },
    ],
  },

  // --- FULLSTACK (7 additional) ---
  {
    email: 'dumisani.radebe@standardbank.co.za',
    fullName: 'Dumisani Radebe',
    primaryRole: 'FULLSTACK',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-20'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 5 },
      { skill: 'Node.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'PostgreSQL', proficiencyLevel: 4 },
      { skill: 'Docker', proficiencyLevel: 4 },
      { skill: 'GraphQL', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'marlene.viljoen@standardbank.co.za',
    fullName: 'Marlene Viljoen',
    primaryRole: 'FULLSTACK',
    currentAllocationPercentage: 40,
    availabilityDate: new Date('2024-03-01'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 4 },
      { skill: 'Node.js', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'Next.js', proficiencyLevel: 5 },
      { skill: 'AWS', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'siyabonga.mkhize@standardbank.co.za',
    fullName: 'Siyabonga Mkhize',
    primaryRole: 'FULLSTACK',
    currentAllocationPercentage: 70,
    availabilityDate: new Date('2024-04-15'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 4 },
      { skill: 'Node.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'PostgreSQL', proficiencyLevel: 5 },
      { skill: 'Docker', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'suresh.pillay@standardbank.co.za',
    fullName: 'Suresh Pillay',
    primaryRole: 'FULLSTACK',
    currentAllocationPercentage: 20,
    availabilityDate: new Date('2024-02-10'),
    geographicLocation: 'Durban, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 5 },
      { skill: 'Node.js', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'AWS', proficiencyLevel: 4 },
      { skill: 'GraphQL', proficiencyLevel: 5 },
      { skill: 'Next.js', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'lindiwe.maseko@standardbank.co.za',
    fullName: 'Lindiwe Maseko',
    primaryRole: 'FULLSTACK',
    currentAllocationPercentage: 100,
    availabilityDate: new Date('2024-06-15'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 4 },
      { skill: 'Node.js', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'PostgreSQL', proficiencyLevel: 3 },
      { skill: 'Docker', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'grant.september@standardbank.co.za',
    fullName: 'Grant September',
    primaryRole: 'FULLSTACK',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-28'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 5 },
      { skill: 'Node.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'PostgreSQL', proficiencyLevel: 4 },
      { skill: 'AWS', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'mpho.tshikovhi@standardbank.co.za',
    fullName: 'Mpho Tshikovhi',
    primaryRole: 'FULLSTACK',
    currentAllocationPercentage: 30,
    availabilityDate: new Date('2024-02-28'),
    geographicLocation: 'Polokwane, ZA',
    skills: [
      { skill: 'React', proficiencyLevel: 4 },
      { skill: 'Node.js', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'MongoDB', proficiencyLevel: 4 },
      { skill: 'Next.js', proficiencyLevel: 3 },
    ],
  },

  // --- DESIGN (7 additional) ---
  {
    email: 'nokuthula.cele@standardbank.co.za',
    fullName: 'Nokuthula Cele',
    primaryRole: 'DESIGN',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-15'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Figma', proficiencyLevel: 5 },
      { skill: 'UX Research', proficiencyLevel: 4 },
      { skill: 'Prototyping', proficiencyLevel: 5 },
      { skill: 'User Testing', proficiencyLevel: 4 },
      { skill: 'Design Systems', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'francois.duplessis@standardbank.co.za',
    fullName: 'Francois du Plessis',
    primaryRole: 'DESIGN',
    currentAllocationPercentage: 60,
    availabilityDate: new Date('2024-04-01'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'Figma', proficiencyLevel: 5 },
      { skill: 'Sketch', proficiencyLevel: 4 },
      { skill: 'Design Systems', proficiencyLevel: 5 },
      { skill: 'Accessibility', proficiencyLevel: 5 },
      { skill: 'Prototyping', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'keabetswe.motlanthe@standardbank.co.za',
    fullName: 'Keabetswe Motlanthe',
    primaryRole: 'DESIGN',
    currentAllocationPercentage: 30,
    availabilityDate: new Date('2024-02-20'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Figma', proficiencyLevel: 4 },
      { skill: 'UX Research', proficiencyLevel: 5 },
      { skill: 'User Testing', proficiencyLevel: 5 },
      { skill: 'Accessibility', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'ashwin.maharaj@standardbank.co.za',
    fullName: 'Ashwin Maharaj',
    primaryRole: 'DESIGN',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-10'),
    geographicLocation: 'Durban, ZA',
    skills: [
      { skill: 'Figma', proficiencyLevel: 5 },
      { skill: 'UX Research', proficiencyLevel: 4 },
      { skill: 'Design Systems', proficiencyLevel: 5 },
      { skill: 'Prototyping', proficiencyLevel: 5 },
      { skill: 'Sketch', proficiencyLevel: 3 },
      { skill: 'User Testing', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'thembi.shabalala@standardbank.co.za',
    fullName: 'Thembi Shabalala',
    primaryRole: 'DESIGN',
    currentAllocationPercentage: 50,
    availabilityDate: new Date('2024-03-20'),
    geographicLocation: 'Pretoria, ZA',
    skills: [
      { skill: 'Figma', proficiencyLevel: 5 },
      { skill: 'Accessibility', proficiencyLevel: 5 },
      { skill: 'UX Research', proficiencyLevel: 5 },
      { skill: 'Design Systems', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'wayne.adams@standardbank.co.za',
    fullName: 'Wayne Adams',
    primaryRole: 'DESIGN',
    currentAllocationPercentage: 90,
    availabilityDate: new Date('2024-07-01'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'Figma', proficiencyLevel: 4 },
      { skill: 'Sketch', proficiencyLevel: 5 },
      { skill: 'Prototyping', proficiencyLevel: 4 },
      { skill: 'User Testing', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'palesa.moagi@standardbank.co.za',
    fullName: 'Palesa Moagi',
    primaryRole: 'DESIGN',
    currentAllocationPercentage: 10,
    availabilityDate: new Date('2024-02-01'),
    geographicLocation: 'Bloemfontein, ZA',
    skills: [
      { skill: 'Figma', proficiencyLevel: 5 },
      { skill: 'Adobe XD', proficiencyLevel: 4 },
      { skill: 'UX Research', proficiencyLevel: 4 },
      { skill: 'Prototyping', proficiencyLevel: 5 },
      { skill: 'Design Systems', proficiencyLevel: 3 },
    ],
  },

  // --- QA (7 additional) ---
  {
    email: 'vuyelwa.magwaza@standardbank.co.za',
    fullName: 'Vuyelwa Magwaza',
    primaryRole: 'QA',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-10'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Playwright', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'Cypress', proficiencyLevel: 4 },
      { skill: 'API Testing', proficiencyLevel: 5 },
      { skill: 'CI/CD', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'danie.vanwyk@standardbank.co.za',
    fullName: 'Danie van Wyk',
    primaryRole: 'QA',
    currentAllocationPercentage: 40,
    availabilityDate: new Date('2024-03-01'),
    geographicLocation: 'Pretoria, ZA',
    skills: [
      { skill: 'Selenium', proficiencyLevel: 5 },
      { skill: 'JUnit', proficiencyLevel: 5 },
      { skill: 'Performance Testing', proficiencyLevel: 4 },
      { skill: 'API Testing', proficiencyLevel: 4 },
      { skill: 'Load Testing', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'ntombi.zwane@standardbank.co.za',
    fullName: 'Ntombi Zwane',
    primaryRole: 'QA',
    currentAllocationPercentage: 80,
    availabilityDate: new Date('2024-05-15'),
    geographicLocation: 'Durban, ZA',
    skills: [
      { skill: 'Playwright', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'Performance Testing', proficiencyLevel: 5 },
      { skill: 'Load Testing', proficiencyLevel: 5 },
      { skill: 'CI/CD', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'riaan.delange@standardbank.co.za',
    fullName: 'Riaan de Lange',
    primaryRole: 'QA',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-25'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'Cypress', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'API Testing', proficiencyLevel: 5 },
      { skill: 'Selenium', proficiencyLevel: 4 },
      { skill: 'CI/CD', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'busisiwe.mthethwa@standardbank.co.za',
    fullName: 'Busisiwe Mthethwa',
    primaryRole: 'QA',
    currentAllocationPercentage: 30,
    availabilityDate: new Date('2024-02-15'),
    geographicLocation: 'Port Elizabeth, ZA',
    skills: [
      { skill: 'Playwright', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'Cypress', proficiencyLevel: 4 },
      { skill: 'Performance Testing', proficiencyLevel: 3 },
      { skill: 'API Testing', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'rendani.tshivhase@standardbank.co.za',
    fullName: 'Rendani Tshivhase',
    primaryRole: 'QA',
    currentAllocationPercentage: 60,
    availabilityDate: new Date('2024-04-10'),
    geographicLocation: 'Polokwane, ZA',
    skills: [
      { skill: 'Selenium', proficiencyLevel: 5 },
      { skill: 'JUnit', proficiencyLevel: 4 },
      { skill: 'API Testing', proficiencyLevel: 5 },
      { skill: 'Performance Testing', proficiencyLevel: 4 },
      { skill: 'Load Testing', proficiencyLevel: 3 },
      { skill: 'CI/CD', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'karen.koen@standardbank.co.za',
    fullName: 'Karen Koen',
    primaryRole: 'QA',
    currentAllocationPercentage: 10,
    availabilityDate: new Date('2024-02-05'),
    geographicLocation: 'Bloemfontein, ZA',
    skills: [
      { skill: 'Playwright', proficiencyLevel: 4 },
      { skill: 'Cypress', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
      { skill: 'API Testing', proficiencyLevel: 5 },
    ],
  },

  // --- DATA (7 additional) ---
  {
    email: 'tebogo.mashego@standardbank.co.za',
    fullName: 'Tebogo Mashego',
    primaryRole: 'DATA',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-18'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Python', proficiencyLevel: 5 },
      { skill: 'SQL', proficiencyLevel: 5 },
      { skill: 'Spark', proficiencyLevel: 4 },
      { skill: 'Data Modeling', proficiencyLevel: 5 },
      { skill: 'ETL', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'maria.dupreez@standardbank.co.za',
    fullName: 'Maria du Preez',
    primaryRole: 'DATA',
    currentAllocationPercentage: 50,
    availabilityDate: new Date('2024-03-10'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'Python', proficiencyLevel: 4 },
      { skill: 'SQL', proficiencyLevel: 5 },
      { skill: 'Tableau', proficiencyLevel: 5 },
      { skill: 'Power BI', proficiencyLevel: 4 },
      { skill: 'Data Modeling', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'sibusiso.mhlanga@standardbank.co.za',
    fullName: 'Sibusiso Mhlanga',
    primaryRole: 'DATA',
    currentAllocationPercentage: 70,
    availabilityDate: new Date('2024-04-20'),
    geographicLocation: 'Pretoria, ZA',
    skills: [
      { skill: 'Python', proficiencyLevel: 5 },
      { skill: 'Kafka', proficiencyLevel: 5 },
      { skill: 'Spark', proficiencyLevel: 5 },
      { skill: 'SQL', proficiencyLevel: 4 },
      { skill: 'Machine Learning', proficiencyLevel: 3 },
      { skill: 'ETL', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'nkosazana.buthelezi@standardbank.co.za',
    fullName: 'Nkosazana Buthelezi',
    primaryRole: 'DATA',
    currentAllocationPercentage: 20,
    availabilityDate: new Date('2024-02-08'),
    geographicLocation: 'Durban, ZA',
    skills: [
      { skill: 'Python', proficiencyLevel: 5 },
      { skill: 'SQL', proficiencyLevel: 4 },
      { skill: 'Machine Learning', proficiencyLevel: 5 },
      { skill: 'Data Modeling', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'jan.steyn@standardbank.co.za',
    fullName: 'Jan Steyn',
    primaryRole: 'DATA',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-12'),
    geographicLocation: 'Bloemfontein, ZA',
    skills: [
      { skill: 'SQL', proficiencyLevel: 5 },
      { skill: 'Power BI', proficiencyLevel: 5 },
      { skill: 'Tableau', proficiencyLevel: 4 },
      { skill: 'Python', proficiencyLevel: 4 },
      { skill: 'Data Modeling', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'mpumi.xaba@standardbank.co.za',
    fullName: 'Mpumi Xaba',
    primaryRole: 'DATA',
    currentAllocationPercentage: 100,
    availabilityDate: new Date('2024-08-01'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Python', proficiencyLevel: 5 },
      { skill: 'Spark', proficiencyLevel: 5 },
      { skill: 'Kafka', proficiencyLevel: 4 },
      { skill: 'SQL', proficiencyLevel: 4 },
      { skill: 'Machine Learning', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'wisani.maluleke@standardbank.co.za',
    fullName: 'Wisani Maluleke',
    primaryRole: 'DATA',
    currentAllocationPercentage: 40,
    availabilityDate: new Date('2024-03-05'),
    geographicLocation: 'Polokwane, ZA',
    skills: [
      { skill: 'Python', proficiencyLevel: 4 },
      { skill: 'SQL', proficiencyLevel: 5 },
      { skill: 'ETL', proficiencyLevel: 5 },
      { skill: 'Data Modeling', proficiencyLevel: 4 },
      { skill: 'TypeScript', proficiencyLevel: 4 },
    ],
  },

  // --- PLATFORM (7 additional) ---
  {
    email: 'kobus.vanrensburg@standardbank.co.za',
    fullName: 'Kobus van Rensburg',
    primaryRole: 'PLATFORM',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-15'),
    geographicLocation: 'Pretoria, ZA',
    skills: [
      { skill: 'AWS', proficiencyLevel: 5 },
      { skill: 'Terraform', proficiencyLevel: 5 },
      { skill: 'Docker', proficiencyLevel: 5 },
      { skill: 'Kubernetes', proficiencyLevel: 4 },
      { skill: 'Linux', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'nomvula.mahlangu@standardbank.co.za',
    fullName: 'Nomvula Mahlangu',
    primaryRole: 'PLATFORM',
    currentAllocationPercentage: 60,
    availabilityDate: new Date('2024-04-01'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'Azure', proficiencyLevel: 5 },
      { skill: 'Docker', proficiencyLevel: 4 },
      { skill: 'Kubernetes', proficiencyLevel: 5 },
      { skill: 'CI/CD', proficiencyLevel: 5 },
      { skill: 'Terraform', proficiencyLevel: 4 },
      { skill: 'Monitoring', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'andre.coetzee@standardbank.co.za',
    fullName: 'Andre Coetzee',
    primaryRole: 'PLATFORM',
    currentAllocationPercentage: 20,
    availabilityDate: new Date('2024-02-10'),
    geographicLocation: 'Cape Town, ZA',
    skills: [
      { skill: 'GCP', proficiencyLevel: 5 },
      { skill: 'Docker', proficiencyLevel: 5 },
      { skill: 'Kubernetes', proficiencyLevel: 5 },
      { skill: 'Terraform', proficiencyLevel: 4 },
      { skill: 'Ansible', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'thulani.mthombeni@standardbank.co.za',
    fullName: 'Thulani Mthombeni',
    primaryRole: 'PLATFORM',
    currentAllocationPercentage: 80,
    availabilityDate: new Date('2024-05-15'),
    geographicLocation: 'Durban, ZA',
    skills: [
      { skill: 'AWS', proficiencyLevel: 4 },
      { skill: 'Docker', proficiencyLevel: 5 },
      { skill: 'CI/CD', proficiencyLevel: 5 },
      { skill: 'Linux', proficiencyLevel: 5 },
      { skill: 'Monitoring', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'lineo.mothibe@standardbank.co.za',
    fullName: 'Lineo Mothibe',
    primaryRole: 'PLATFORM',
    currentAllocationPercentage: 0,
    availabilityDate: new Date('2024-01-22'),
    geographicLocation: 'Bloemfontein, ZA',
    skills: [
      { skill: 'AWS', proficiencyLevel: 5 },
      { skill: 'Azure', proficiencyLevel: 4 },
      { skill: 'Terraform', proficiencyLevel: 5 },
      { skill: 'Docker', proficiencyLevel: 4 },
      { skill: 'CI/CD', proficiencyLevel: 4 },
    ],
  },
  {
    email: 'xolani.hlongwane@standardbank.co.za',
    fullName: 'Xolani Hlongwane',
    primaryRole: 'PLATFORM',
    currentAllocationPercentage: 30,
    availabilityDate: new Date('2024-02-28'),
    geographicLocation: 'Port Elizabeth, ZA',
    skills: [
      { skill: 'Kubernetes', proficiencyLevel: 5 },
      { skill: 'Docker', proficiencyLevel: 5 },
      { skill: 'AWS', proficiencyLevel: 4 },
      { skill: 'Ansible', proficiencyLevel: 5 },
      { skill: 'Linux', proficiencyLevel: 5 },
      { skill: 'Monitoring', proficiencyLevel: 3 },
    ],
  },
  {
    email: 'fikile.nxumalo@standardbank.co.za',
    fullName: 'Fikile Nxumalo',
    primaryRole: 'PLATFORM',
    currentAllocationPercentage: 10,
    availabilityDate: new Date('2024-02-01'),
    geographicLocation: 'Johannesburg, ZA',
    skills: [
      { skill: 'GCP', proficiencyLevel: 4 },
      { skill: 'AWS', proficiencyLevel: 5 },
      { skill: 'Docker', proficiencyLevel: 4 },
      { skill: 'Terraform', proficiencyLevel: 5 },
      { skill: 'CI/CD', proficiencyLevel: 5 },
    ],
  },
  {
    email: 'tlou.malatji@standardbank.co.za',
    fullName: 'Tlou Malatji',
    primaryRole: 'QA',
    currentAllocationPercentage: 50,
    availabilityDate: new Date('2024-03-18'),
    geographicLocation: 'Polokwane, ZA',
    skills: [
      { skill: 'Playwright', proficiencyLevel: 5 },
      { skill: 'TypeScript', proficiencyLevel: 5 },
      { skill: 'Selenium', proficiencyLevel: 3 },
      { skill: 'Performance Testing', proficiencyLevel: 4 },
      { skill: 'CI/CD', proficiencyLevel: 4 },
    ],
  },
];

async function main(): Promise<void> {
  console.log('🌱 Seeding database...');

  // Clear existing data (order matters due to foreign key constraints)
  await prisma.squadMembership.deleteMany();
  await prisma.scoringResult.deleteMany();
  await prisma.proposedSquad.deleteMany();
  await prisma.demandRequest.deleteMany();
  await prisma.skillProfile.deleteMany();
  await prisma.employeeProfile.deleteMany();

  for (const emp of employees) {
    await prisma.employeeProfile.create({
      data: {
        email: emp.email,
        fullName: emp.fullName,
        primaryRole: emp.primaryRole,
        currentAllocationPercentage: emp.currentAllocationPercentage,
        availabilityDate: emp.availabilityDate,
        geographicLocation: emp.geographicLocation,
        skills: {
          create: emp.skills.map((s) => ({
            skill: s.skill,
            proficiencyLevel: s.proficiencyLevel,
          })),
        },
      },
    });
  }

  console.log(`✅ Seeded ${employees.length} employees with skills`);
}

main()
  .catch((e) => {
    console.error('[seed] Failed to seed database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
